sudo: required
services:
    - docker
    
before_install:
    - docker build -t anujaga/docker-nodeapp -f Dockerfile.dev .
    
script:
    - docker run anujaga/docker-nodeapp npm run test -- --coverage